<form action="" method='get'>
    <div class='row p-4 '>
        <div class="col">
            <h4>search</h4>
            <input type="text" name="search">
            <input type="submit" value="submit">
        </div>
        <div class="col">
            <a href="/index/addproduct" class="btn btn-primary">add</a>
            <a href="/" class="btn btn-danger">home</a>
        </div>
        <hr>
    </div>
</form>
<table class="table">
    <thead class='bg-dark text-white fw-bold '>
        <tr>
            <th scope="col">name</th>
            <th scope="col">category</th>
            <th scope="col">price</th>
            <th scope="col">stock</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        <?php

        foreach ($products as $idx => $product) {
        ?>

            <tr>
                <form action="" method="post">
                    <td>
                        <p><?php echo $product->name ?></p>
                    </td>
                    <td>
                        <p><?php echo $product->category ?></p>
                    </td>
                    <td>
                        <p><?php echo $product->price ?></p>
                    </td>
                    <td>
                        <p><?php echo $product->stock ?></p>
                    </td>
                    <td>
                        <span class="btn btn-primary viewProduct" data-toggle="modal" data-target="#myModal" data-id="<?php echo $product->_id ?>"> view</span>


                    </td>
                </form>



            </tr>
        <?php }
        ?>
    </tbody>
</table>



<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h3 id='pid' class='float-left'></h3>
                <button type="button" class="btn btn-danger float-right" data-dismiss="modal">X</button>
            </div>
            <div class="modal-body ">
                <form class='productData' action='' method='post'>


                </form>
            </div>

        </div>

    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="../public/js/script.js"></script>