<div class="row shadow-md bg-dark">
    <a href="/" class='btn  btn-primary float-right col'>products</a>
    <a href="/index/addproduct" class='btn btn-success ms-3 float-right col'>add product</a>
    <a href="/order" class='btn btn-danger ms-3 float-right col'>orders</a>
    <a href="/order/addorder" class='btn btn-secondary ms-3 float-right col'>add order</a>
</div>

<h2>Place Order</h2>
<div class='row'>
    <div class="col-7 ">
        <form action="" method="post">
            <div id='addForm'>
                <div class="mb-3">
                    <label for="name" class="form-label">name</label>
                    <input type="text" class="form-control" name="name" aria-describedby="name" required>
                </div>

                <div class="mb-3">
                    <label for="quantity" class="form-label">Quantity</label>
                    <input type="number" class="form-control" id='stock' min=1 name='quantity' required>
                </div>

                <div class="mb-3">
                    <label for="product" class="form-label">Select Product</label>
                    <select name="product" id='products' class='btn' required>

                    </select>
                </div>
                <input type="hidden" name="status" value='ordered'>
                <input type="hidden" name="product id" id='pid'>
                <div class="variation"></div>
            </div>

            <button type="submit" class="btn btn-primary btn-lg">Create Order</button>
        </form>

    </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="../public/js/order.js"></script>