<div class="row shadow-md bg-dark">
    <a href="/" class='btn  btn-primary float-right col'><?php echo $locale->_('products')  ?></a>
    <a href="/index/addproduct" class='btn btn-success ms-3 float-right col'><?php echo $locale->_('add') . " " . $locale->_('product') ?></a>
    <a href="/order" class='btn btn-danger ms-3 float-right col'><?php echo $locale->_('orders') ?></a>
    <a href="/order/addorder" class='btn btn-secondary ms-3 float-right col'><?php echo $locale->_('add') . " " . $locale->_('order') ?></a>
</div>


<form action="" method='get' class='pt-5'>
    <div class="row">
        <div class="col-4">
            <label for="date"><?php echo $locale->_('dateselect') ?>
                <select name="date" id='date'>
                    <option name='date' value="<?php echo date_format(date_sub(date_create(date("Y-m-d")), date_interval_create_from_date_string("5000 days")), "Y-m-d"); ?>">All</option>
                    <option name='date' value="<?php echo date("Y-m-d") ?>">Today</option>
                    <option name='date' value="<?php echo date_format(date_sub(date_create(date("Y-m-d")), date_interval_create_from_date_string("7 days")), "Y-m-d"); ?>">This week</option>
                    <option name='date' value="<?php echo date_format(date_sub(date_create(date("Y-m-d")), date_interval_create_from_date_string("30 days")), "Y-m-d"); ?>">This month</option>
                    <option value="custom" name='date'>custom</option>
                </select></label>
        </div>
        <div class="col-8">
            <label><?php echo $locale->_('datecustom') ?> - </label>
            <label for="start" class='px-2'> From - <input type="text" name="start" placeholder="YYYY-MM-DD " class='customDate' required disabled></label>
            <label for="end" class='px-2'> To - <input type="text" name="end" placeholder="YYYY-MM-DD " class='customDate' required disabled></label>
        </div>
    </div>
    <div class="row">
        <button class='col btn border' value="all" name='statusfilter'>all</button>
        <button class='col btn border' value="paid" name='statusfilter'>paid</button>
        <button class='col btn border' value="processing" name='statusfilter'>processing</button>
        <button class='col btn border' value="dispatched" name='statusfilter'>dispatched</button>
        <button class='col btn border' value="shipped" name='statusfilter'>shipped</button>
        <button class='col btn border' value="refunded" name='statusfilter'>refunded</button>
    </div>
</form>


</div>
<table class="table">
    <thead class='bg-dark text-white fw-bold '>
        <tr>
            <th scope="col"><?php echo $locale->_('customer') . " " . $locale->_('name') ?></th>
            <th scope="col"><?php echo $locale->_('product_id') ?></th>
            <th scope="col"><?php echo $locale->_('quantity') ?></th>
            <th scope="col"><?php echo $locale->_('status') ?></th>

        </tr>
    </thead>
    <tbody>

        <?php

        foreach ($orders as $idx => $order) {
        ?>

            <tr>

                <td>
                    <p><?php echo $order->name ?></p>
                </td>
                <td>
                    <p><?php echo $order->product_id ?></p>
                </td>
                <td>
                    <p><?php echo $order->quantity ?></p>
                </td>
                <td>

                    <div class="dropdown show">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <?php echo $order->status ?>
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="/order/updatestatus?id=<?php echo $order->_id . "&status=paid"; ?>">Paid</a>
                            <a class="dropdown-item" href="/order/updatestatus?id=<?php echo $order->_id . "&status=processing"; ?>">Processing</a>
                            <a class="dropdown-item" href="/order/updatestatus?id=<?php echo $order->_id . "&status=dispatched"; ?>">Dispatched</a>
                            <a class="dropdown-item" href="/order/updatestatus?id=<?php echo $order->_id . "&status=shipped"; ?>">Shipped</a>
                            <a class="dropdown-item" href="/order/updatestatus?id=<?php echo $order->_id . "&status=refunded"; ?>">Refunded</a>
                        </div>
                    </div>


                </td>




            </tr>
        <?php }
        ?>
    </tbody>
</table>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="../public/js/order.js"></script>